// <auto-generated />
namespace FireSys.DB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ZapisnikStatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ZapisnikStatus));
        
        string IMigrationMetadata.Id
        {
            get { return "201802170856024_ZapisnikStatus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
